import { RouterProvider, createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen"; // This is generated by the TanStack Router Vite plugin

const router = createRouter({
  routeTree,
});

function App() {
  return (
    <RouterProvider router={router}>
      {/* Your route components will be rendered here */}
    </RouterProvider>
  );
}

export default App;
